# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
module(
    name = "os_images",
    version = "1.0",
)

# ------------------------------------------------------------------------------
# QNX toolchains

bazel_dep(name = "score_rules_imagefs", version = "0.0.1")
local_path_override(
    module_name = "score_rules_imagefs",
    path = "../../score_rules_imagefs",
)

imagefs = use_extension("@score_rules_imagefs//extensions:imagefs.bzl", "imagefs", dev_dependency = True)
imagefs.sdp(
    name = "score_qnx_imagefs_toolchain_pkg",
    url = "https://artifactory.boschdevcloud.com/artifactory/vrte-conan-releases-local/vrte-ci/qnx-sdp8/2025.12.1/tools/39a6e8fc924e6c3cc8eedd34cb02798a/package/3d2268685caec3e0b869469fb726217a3d45aba6/4a0afc64da694d0eb33a804af7429e5d/conan_package.tgz",
    sha256 = "03a0afc329e4cbc78a1d0829009fad0de47fb335189b36c81670bfd4ec0e67de",
)

imagefs.toolchain(
    name = "score_qnx_imagefs_toolchain",
    sdp_to_import = "@score_qnx_imagefs_toolchain_pkg",
    sdp_version = "8.0.0",
    target_cpu = "aarch64",
    target_os = "qnx",
    type = "ifs",
    )
imagefs.toolchain(
    name = "score_qnx_fatfs_toolchain",
    sdp_to_import = "@score_qnx_imagefs_toolchain_pkg",
    sdp_version = "8.0.0",
    target_cpu = "aarch64",
    target_os = "qnx",
    type = "fatfs",
    )
imagefs.toolchain(
    name = "score_qnx_qnx6fs_toolchain",
    sdp_to_import = "@score_qnx_imagefs_toolchain_pkg",
    sdp_version = "8.0.0",
    target_cpu = "aarch64",
    target_os = "qnx",
    type = "qnx6fs",
    )
imagefs.toolchain(
    name = "score_qnx_diskimage_toolchain",
    sdp_to_import = "@score_qnx_imagefs_toolchain_pkg",
    sdp_version = "8.0.0",
    target_cpu = "aarch64",
    target_os = "qnx",
    type = "diskimage",
    )

use_repo(
    imagefs,
    "score_qnx_imagefs_toolchain_pkg",
    "score_qnx_imagefs_toolchain",
    "score_qnx_fatfs_toolchain",
    "score_qnx_qnx6fs_toolchain",
    "score_qnx_diskimage_toolchain",
)

register_toolchains(
    "@score_qnx_imagefs_toolchain//:ifs-aarch64-qnx-sdp_8.0.0",
    "@score_qnx_fatfs_toolchain//:fatfs-aarch64-qnx-sdp_8.0.0",
    "@score_qnx_qnx6fs_toolchain//:qnx6fs-aarch64-qnx-sdp_8.0.0",
    "@score_qnx_diskimage_toolchain//:diskimage-aarch64-qnx-sdp_8.0.0",
)


# ------------------------------------------------------------------------------
# External BSP archives
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Replace the closed-source BSP ZIP with the open-source GitHub repo
http_archive(
    name = "qnx8_bsp_rpi4_src",
    url = "https://github.com/qnx/bsp_raspberrypi-bcm2711-rpi4/archive/refs/heads/main.tar.gz",
    strip_prefix = "bsp_raspberrypi-bcm2711-rpi4-main",
    # sha256 = "<compute after first download>",
    build_file_content = """
# Expose the Makefile as a single-file target for $(location) in genrule
exports_files(["Makefile"])

# Expose all BSP sources so the genrule can access them
filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
""",
)

# ------------------------------------------------------------------------------
# External RPI4 firmware archive
http_archive(
    name = "rpi4_firmware_files",
    url = "https://github.com/raspberrypi/firmware/releases/download/1.20250915/raspi-firmware_1.20250915.orig.tar.xz",
    strip_prefix = "raspi-firmware-1.20250915/boot",
    sha256 = "545b5f8a624b98222c7b4ef4244ac219845993aba15e49d5440b21ccd722340e",
    build_file_content = """
exports_files(["fixup4.dat"])

filegroup(
    name = "rpi4_files",
    srcs = [
        "start4.elf",
        "start4x.elf",
        "start4db.elf", 
        "start4cd.elf",
        "fixup4.dat",
        "fixup4x.dat",
        "fixup4db.dat",
        "fixup4cd.dat",
    ],
    visibility = ["//visibility:public"],
)
""",
)
# External RPI4 dtb file
http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "rpi4_dtb",
    url = "https://github.com/raspberrypi/firmware/raw/refs/heads/stable/boot/bcm2711-rpi-4-b.dtb",
    downloaded_file_path = "bcm2711-rpi-4-b.dtb",
    # sha256 = "<compute after first download>",
)

# ------------------------------------------------------------------------------
# General purpose Bazel extensions

# Compliance and licensing toolchain
bazel_dep(name = "score_dash_license_checker", version = "0.1.2")
bazel_dep(name = "score_cr_checker", version = "0.2.2")
bazel_dep(name = "score_python_basics", version = "0.3.0")
bazel_dep(name = "score_starpls_lsp", version = "0.1.0")

# Formatting and linting helpers
bazel_dep(name = "score_format_checker", version = "0.1.1")
bazel_dep(name = "aspect_rules_lint", version = "1.3.1")
bazel_dep(name = "buildifier_prebuilt", version = "7.3.1")

# Documentation tools
bazel_dep(name = "score_docs_as_code", version = "0.2.4")

bazel_dep(name = "score_bazel_platforms", version = "0.0.3")