#!/bin/bash
# run-qemu-qemu-arm64virt.sh

# ------------------------------------------
# General QEMU settings
QEMU_BIN=qemu-system-aarch64
MEM_SIZE=1G     # does not run with less than 1G!
CPU_COUNT=2

# ------------------------------------------
# Images generated by mkqnximage
SCORE_DISK=disk-score.qcow2
SCORE_DISK_SIZE=512M
QNX_IFS=ifs-qemu-arm64virt.bin

if [ ! -f "$SCORE_DISK" ]; then
    qemu-img create -f qcow2 "$SCORE_DISK" $SCORE_DISK_SIZE
    if [ $? -ne 0 ]; then
        echo "Error: Failed to create QEMU disk image $SCORE_DISK"
        exit 1
    fi
fi

# ------------------------------------------
# QEMU user network settings
#   subnet. This value must match the IP address configured in guest QNX. 
NETWORK=192.168.120
#   HOST TCP ports to be forwarded to VM
HOST_SSH_PORT=2210
HOST_QCONN_PORT=8000
HOST_DLT_PORT=3490
HOST_DOIP_PORT=13400
#   IP for SSH port forwarding. This value must match the IP address configured in guest QNX.
VM_IP=$NETWORK.20


# ------------------------------------------
# Launch QEMU
$QEMU_BIN -machine virt-4.2 -cpu cortex-a57 -smp $CPU_COUNT -m $MEM_SIZE \
        -kernel $QNX_IFS \
        -drive file=$SCORE_DISK,if=none,id=drv0 -device virtio-blk-device,drive=drv0 \
        -netdev user,id=net0,net=$NETWORK.0/24,hostfwd=tcp::$HOST_SSH_PORT-$VM_IP:22,hostfwd=tcp::$HOST_QCONN_PORT-$VM_IP:8000,hostfwd=tcp::$HOST_DLT_PORT-$VM_IP:3490,hostfwd=tcp::$HOST_DOIP_PORT-$VM_IP:13400 \
        -device virtio-net-device,mac=52:54:00:12:34:72,netdev=net0 \
        -nographic \
        -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-device,rng=rng0 \
        -serial mon:stdio \
	$*
