#!/bin/bash
# run-qemu-x86_64.sh [<IFS image>]

# ------------------------------------------
# General QEMU settings
QEMU_BIN=qemu-system-x86_64
MEM_SIZE=1G     # does not run with less than 1G!
CPU_COUNT=2

# ------------------------------------------
QNX_IFS=ifs-qemu-x86_64.bin
if [ "$1" != "" ]; then
    QNX_IFS=$1
    # Remove first argument so that additional args can be passed to QEMU
    shift
fi

# ------------------------------------------
# Images generated by mkqnximage
# Get the directory where the IFS image is located
QNX_IFS_DIR="$(dirname "$QNX_IFS")"

SCORE_DISK=disk-score.qcow2
SCORE_DISK_SIZE=512M

if [ ! -f "$SCORE_DISK" ]; then
    qemu-img create -f qcow2 "$SCORE_DISK" $SCORE_DISK_SIZE
    if [ $? -ne 0 ]; then
        echo "Error: Failed to create QEMU disk image $SCORE_DISK"
        exit 1
    fi
fi

# ------------------------------------------
# QEMU user network settings
#   subnet. This value must match the IP address configured in guest QNX. 
NETWORK=192.168.120
#   HOST TCP ports to be forwarded to VM
HOST_SSH_PORT=2210
HOST_QCONN_PORT=8000
HOST_DLT_PORT=3490
HOST_DOIP_PORT=13400
#   IP for SSH port forwarding. This value must match the IP address configured in guest QNX.
VM_IP=$NETWORK.20


# ------------------------------------------
# Launch QEMU
$QEMU_BIN -cpu host -accel kvm -smp $CPU_COUNT -m $MEM_SIZE \
        -kernel $QNX_IFS \
        -drive file=$SCORE_DISK,if=none,id=drv0 -device virtio-blk-pci,drive=drv0 \
        -netdev user,id=net0,net=$NETWORK.0/24,hostfwd=tcp::$HOST_SSH_PORT-$VM_IP:22,hostfwd=tcp::$HOST_QCONN_PORT-$VM_IP:8000,hostfwd=tcp::$HOST_DLT_PORT-$VM_IP:3490,hostfwd=tcp::$HOST_DOIP_PORT-$VM_IP:13400 \
        -device virtio-net-pci,mac=52:54:00:12:34:72,netdev=net0 \
        -nographic \
        -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0 \
        -serial mon:stdio \
        $*
